In [100]:
import os 
import pandas as pd
import numpy as np

In [101]:
df = pd.read_excel('/home/vivek/Desktop/PPG-Analysis/CLEANED_DATA/labels/participant_response.xlsx')

In [102]:
df.shape

(119, 49)

In [103]:
df.columns

Index(['P_Id', 'SPIN Score', 'PBS', 'ATS1_1', 'ATS1_2', 'ATS1_3', 'ATS1_4',
       'ATS1_5', 'AS1_1', 'AS1_2', 'AS1_3', 'AS1_4', 'AS1_5', 'RS1_1', 'RS1_2',
       'RS1_3', 'RS1_4', 'RS1_5', 'ATS2_1', 'ATS2_2', 'ATS2_3', 'ATS2_4',
       'ATS2_5', 'AS2_1', 'AS2_2', 'AS2_3', 'AS2_4', 'AS2_5', 'RS2_1', 'RS2_2',
       'RS2_3', 'RS2_4', 'RS2_5', 'ATS3_1', 'ATS3_2', 'ATS3_3', 'ATS3_4',
       'ATS3_5', 'AS3_1', 'AS3_2', 'AS3_3', 'AS3_4', 'AS3_5', 'RS3_1', 'RS3_2',
       'RS3_3', 'RS3_4', 'RS3_5', 'PS'],
      dtype='object')

In [104]:

# Define the mapping dictionary
mapping = {1: 5, 2: 4, 3: 3, 4: 2, 5: 1, None: None}

In [105]:
# Apply the mapping using map() function
df['AS1_2_changed'] = df['AS1_2'].map(mapping)

In [106]:
df

,P_Id,SPIN Score,PBS,ATS1_1,ATS1_2,ATS1_3,ATS1_4,ATS1_5,AS1_1,AS1_2,...,AS3_3,AS3_4,AS3_5,RS3_1,RS3_2,RS3_3,RS3_4,RS3_5,PS,AS1_2_changed
0,101,17.0,5.0,3.0,3.0,3.0,3.0,4.0,2.0,4.0,...,1.0,4.0,1.0,1.0,4.0,1.0,1.0,1.0,5.0,2.0
1,102,44.0,2.0,1.0,1.0,5.0,3.0,4.0,2.0,4.0,...,4.0,5.0,4.0,5.0,2.0,4.0,5.0,4.0,4.0,2.0
2,103,10.0,3.0,3.0,3.0,3.0,3.0,3.0,1.0,4.0,...,3.0,3.0,3.0,1.0,3.0,3.0,3.0,2.0,4.0,2.0
3,104,10.0,2.0,1.0,4.0,1.0,2.0,1.0,3.0,4.0,...,1.0,2.0,1.0,1.0,4.0,1.0,1.0,1.0,5.0,2.0
4,105,26.0,3.0,4.0,2.0,3.0,4.0,3.0,2.0,4.0,...,4.0,4.0,3.0,3.0,4.0,3.0,3.0,4.0,4.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
114,215,54.0,2.0,2.0,1.0,5.0,4.0,3.0,5.0,1.0,...,5.0,5.0,5.0,4.0,3.0,4.0,5.0,5.0,4.0,5.0
115,216,38.0,2.0,1.0,2.0,5.0,5.0,5.0,5.0,2.0,...,2.0,5.0,5.0,4.0,4.0,4.0,5.0,4.0,3.0,4.0
116,217,52.0,2.0,2.0,2.0,4.0,5.0,4.0,4.0,2.0,...,4.0,5.0,4.0,4.0,2.0,4.0,4.0,4.0,2.0,4.0
117,218,43.0,2.0,1.0,2.0,3.0,5.0,5.0,5.0,2.0,...,2.0,4.0,4.0,2.0,2.0,4.0,4.0,4.0,4.0,4.0
118,219,35.0,3.0,2.0,2.0,4.0,5.0,5.0,3.0,4.0,...,2.0,4.0,3.0,2.0,5.0,1.0,3.0,2.0,3.0,2.0

In [107]:
test_unique_or_not = df['AS1_2'] + df['AS1_2_changed']

In [108]:
test_unique_or_not.unique()

array([ 6., nan])

In [109]:
df['AS1_2'] = df['AS1_2_changed']

In [110]:
df.drop(columns=['AS1_2_changed'], inplace=True)

In [111]:
# Select only the columns you want to sum
columns_to_sum = ['AS1_1', 'AS1_2', 'AS1_3', 'AS1_4', 'AS1_5']

In [112]:
# Sum values across rows for selected columns and store the result in a new column `anxiety_meter`
df['anxiety_meter'] = df[columns_to_sum].sum(axis=1)

In [113]:
# Create 'Anxious' column based on sum condition
df['Anxious'] = (df['anxiety_meter'] >= 16).astype(int)

In [114]:
df.head()

,P_Id,SPIN Score,PBS,ATS1_1,ATS1_2,ATS1_3,ATS1_4,ATS1_5,AS1_1,AS1_2,...,AS3_4,AS3_5,RS3_1,RS3_2,RS3_3,RS3_4,RS3_5,PS,anxiety_meter,Anxious
0,101,17.0,5.0,3.0,3.0,3.0,3.0,4.0,2.0,2.0,...,4.0,1.0,1.0,4.0,1.0,1.0,1.0,5.0,7.0,0
1,102,44.0,2.0,1.0,1.0,5.0,3.0,4.0,2.0,2.0,...,5.0,4.0,5.0,2.0,4.0,5.0,4.0,4.0,16.0,1
2,103,10.0,3.0,3.0,3.0,3.0,3.0,3.0,1.0,2.0,...,3.0,3.0,1.0,3.0,3.0,3.0,2.0,4.0,10.0,0
3,104,10.0,2.0,1.0,4.0,1.0,2.0,1.0,3.0,2.0,...,2.0,1.0,1.0,4.0,1.0,1.0,1.0,5.0,8.0,0
4,105,26.0,3.0,4.0,2.0,3.0,4.0,3.0,2.0,2.0,...,4.0,3.0,3.0,4.0,3.0,3.0,4.0,4.0,15.0,0

In [115]:
df.isnull().sum()

P_Id             0
SPIN Score       8
PBS              8
ATS1_1           8
ATS1_2           8
ATS1_3           8
ATS1_4           8
ATS1_5           8
AS1_1            8
AS1_2            8
AS1_3            9
AS1_4            8
AS1_5            8
RS1_1            8
RS1_2            8
RS1_3            8
RS1_4            8
RS1_5            8
ATS2_1           8
ATS2_2           8
ATS2_3           8
ATS2_4           8
ATS2_5           8
AS2_1            8
AS2_2            8
AS2_3            8
AS2_4            9
AS2_5            8
RS2_1            9
RS2_2            8
RS2_3            8
RS2_4            8
RS2_5            8
ATS3_1           8
ATS3_2           8
ATS3_3           8
ATS3_4           8
ATS3_5           8
AS3_1            9
AS3_2            8
AS3_3            8
AS3_4            8
AS3_5            8
RS3_1            8
RS3_2            8
RS3_3            9
RS3_4            8
RS3_5            8
PS               9
anxiety_meter    0
Anxious          0
dtype: int64

In [116]:
df

,P_Id,SPIN Score,PBS,ATS1_1,ATS1_2,ATS1_3,ATS1_4,ATS1_5,AS1_1,AS1_2,...,AS3_4,AS3_5,RS3_1,RS3_2,RS3_3,RS3_4,RS3_5,PS,anxiety_meter,Anxious
0,101,17.0,5.0,3.0,3.0,3.0,3.0,4.0,2.0,2.0,...,4.0,1.0,1.0,4.0,1.0,1.0,1.0,5.0,7.0,0
1,102,44.0,2.0,1.0,1.0,5.0,3.0,4.0,2.0,2.0,...,5.0,4.0,5.0,2.0,4.0,5.0,4.0,4.0,16.0,1
2,103,10.0,3.0,3.0,3.0,3.0,3.0,3.0,1.0,2.0,...,3.0,3.0,1.0,3.0,3.0,3.0,2.0,4.0,10.0,0
3,104,10.0,2.0,1.0,4.0,1.0,2.0,1.0,3.0,2.0,...,2.0,1.0,1.0,4.0,1.0,1.0,1.0,5.0,8.0,0
4,105,26.0,3.0,4.0,2.0,3.0,4.0,3.0,2.0,2.0,...,4.0,3.0,3.0,4.0,3.0,3.0,4.0,4.0,15.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
114,215,54.0,2.0,2.0,1.0,5.0,4.0,3.0,5.0,5.0,...,5.0,5.0,4.0,3.0,4.0,5.0,5.0,4.0,24.0,1
115,216,38.0,2.0,1.0,2.0,5.0,5.0,5.0,5.0,4.0,...,5.0,5.0,4.0,4.0,4.0,5.0,4.0,3.0,21.0,1
116,217,52.0,2.0,2.0,2.0,4.0,5.0,4.0,4.0,4.0,...,5.0,4.0,4.0,2.0,4.0,4.0,4.0,2.0,19.0,1
117,218,43.0,2.0,1.0,2.0,3.0,5.0,5.0,5.0,4.0,...,4.0,4.0,2.0,2.0,4.0,4.0,4.0,4.0,21.0,1
118,219,35.0,3.0,2.0,2.0,4.0,5.0,5.0,3.0,2.0,...,4.0,3.0,2.0,5.0,1.0,3.0,2.0,3.0,14.0,0

In [117]:
# List of IDs to remove
missing = [110, 131, 136, 174, 182, 185, 197, 206, 177]
# Remove rows where 'P_Id' is in the 'missing' list
df = df[~df['P_Id'].isin(missing)]

In [118]:
df

,P_Id,SPIN Score,PBS,ATS1_1,ATS1_2,ATS1_3,ATS1_4,ATS1_5,AS1_1,AS1_2,...,AS3_4,AS3_5,RS3_1,RS3_2,RS3_3,RS3_4,RS3_5,PS,anxiety_meter,Anxious
0,101,17.0,5.0,3.0,3.0,3.0,3.0,4.0,2.0,2.0,...,4.0,1.0,1.0,4.0,1.0,1.0,1.0,5.0,7.0,0
1,102,44.0,2.0,1.0,1.0,5.0,3.0,4.0,2.0,2.0,...,5.0,4.0,5.0,2.0,4.0,5.0,4.0,4.0,16.0,1
2,103,10.0,3.0,3.0,3.0,3.0,3.0,3.0,1.0,2.0,...,3.0,3.0,1.0,3.0,3.0,3.0,2.0,4.0,10.0,0
3,104,10.0,2.0,1.0,4.0,1.0,2.0,1.0,3.0,2.0,...,2.0,1.0,1.0,4.0,1.0,1.0,1.0,5.0,8.0,0
4,105,26.0,3.0,4.0,2.0,3.0,4.0,3.0,2.0,2.0,...,4.0,3.0,3.0,4.0,3.0,3.0,4.0,4.0,15.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
114,215,54.0,2.0,2.0,1.0,5.0,4.0,3.0,5.0,5.0,...,5.0,5.0,4.0,3.0,4.0,5.0,5.0,4.0,24.0,1
115,216,38.0,2.0,1.0,2.0,5.0,5.0,5.0,5.0,4.0,...,5.0,5.0,4.0,4.0,4.0,5.0,4.0,3.0,21.0,1
116,217,52.0,2.0,2.0,2.0,4.0,5.0,4.0,4.0,4.0,...,5.0,4.0,4.0,2.0,4.0,4.0,4.0,2.0,19.0,1
117,218,43.0,2.0,1.0,2.0,3.0,5.0,5.0,5.0,4.0,...,4.0,4.0,2.0,2.0,4.0,4.0,4.0,4.0,21.0,1
118,219,35.0,3.0,2.0,2.0,4.0,5.0,5.0,3.0,2.0,...,4.0,3.0,2.0,5.0,1.0,3.0,2.0,3.0,14.0,0

In [119]:
# Create a new DataFrame with 'P_Id', 'Anxious' and 'anxiety_meter' columns
result_df = df[['P_Id', 'anxiety_meter', 'Anxious']]

In [120]:
csv_file_path = '/home/vivek/Desktop/PPG-Analysis/CLEANED_DATA/labels/labels.csv'

In [121]:
result_df.to_csv(csv_file_path, index=False)